

default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/production
  username: miguel
  password: sunny
  host: localhost

test:
  <<: *default
  database: db/production
  username: miguel
  password: sunny
  host: localhost

production:
  <<: *default
  database: db/production
  username: miguel
  password: sunny
  host: localhost
